// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Errors Helpers sanitizeError Sanitizes current path from error stracktraces 1`] = `"{\\"stack\\":\\"Error: this is a test\\\\n    at Object.it ($PWD/src/__tests__/error-helpers.js:37:15)\\\\n    at Object.asyncJestTest (/Users/sidharthachatterjee/Code/gatsby/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)\\\\n    at resolve (/Users/sidharthachatterjee/Code/gatsby/node_modules/jest-jasmine2/build/queueRunner.js:41:12)\\\\n    at new Promise (<anonymous>)\\\\n    at mapper (/Users/sidharthachatterjee/Code/gatsby/node_modules/jest-jasmine2/build/queueRunner.js:26:19)\\\\n    at promise.then (/Users/sidharthachatterjee/Code/gatsby/node_modules/jest-jasmine2/build/queueRunner.js:71:41)\\\\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)\\",\\"message\\":\\"this is a test\\"}"`;
